[build-system]

requires = ['setuptools', 'wheel']
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]

testpaths = [
    "tests"
    ]

[tools.mypy]

mypy_path = "src"

ignore_missing_imports = true
